# Pizza API

## To use these HTTP endpoint install the REST Client plugin in VSCode.

### Get all the Pizzas from the API

GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=TendaniMamadi


### Get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/hlsgLlF7tY/get

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "hlsgLlF7tY",
	"pizza_id" : 2
}

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "hlsgLlF7tY",
	"pizza_id" : 18
}

### Remove a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
content-type: application/json

{
	"cart_code" : "hlsgLlF7tY",
	"pizza_id" : 11
}

### GET all the carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/Andrew

### GET all the active carts for a user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/Lindani/active


### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay	
content-type: application/json

{
	"cart_code" : "hlsgLlF7tY",
	"amount" : 100
}

